version: '3.7'

services:
  polls_postgres:
    image: bitnami/postgresql:latest
    container_name: polls_postgres
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - polls_pg_data:/bitnami/postgresql
    networks:
      - polls_network
    restart: always

  polls_redis:
    image: bitnami/redis:latest
    container_name: polls_redis
    env_file:
      - ./.env
    ports:
      - '6379:6379'
    volumes:
      - 'polls_redis_data:/bitnami/redis/data'
    networks:
      - polls_network
    restart: always

  polls:
      image: polls
      container_name: polls
      build:
        context: .
        dockerfile: ./Dockerfile
      expose:
        - 3333
      ports:
        - '3333:3333'
      env_file:
        - ./.env
      networks:
        - polls_network
      depends_on:
        - polls_postgres
        - polls_redis
      command: sh -c "yarn prisma:migrate && yarn start"

volumes:
  polls_pg_data:
  polls_redis_data:

networks:
  polls_network:
    driver: bridge